name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown -R ubuntu:ubuntu ~/resume-builder/app
            cd ~/resume-builder/app
            git pull origin master
            cd frontend
            npm install
            npm run build
            pkill -f "npm start" || true
            fuser -k 3001/tcp || true
            sleep 2
            cd ~/resume-builder
            docker compose down
            docker compose up -d
            docker compose ps